const materitiga = [
  {
    id: "1",
    bab: "Bab 3",
    judul: "A.	Operasi Aritmatika Bilangan Biner",
    des1: "\t\t1.\tPenjumlahan Bilangan Biner\n\nPenjumlahan bilangan biner dapat dilakukan dengan cara yang sama seperti halnya penjumlahan bilangan desimal. Penjumlahan bilangan desimal dapat dilakukan dengan cara sebagai berikut:\n1)\tDigit-digit dan bilangan-bilangan desimal dijumlahkan satu per satu mulai posisi kolom paling kanan.\n2)\t\tBila hasil penjumlahan antar kolom melebihi nilai 9, maka dikurangi dengan nilai 10 untuk disimpan ke penjumlahan kolom berikutnya.\nMisalnya, 18 + 44 = 62, dengan menggunakan Iangkah-langkah di atas bisa diterapkan sebagaiberikut.\n8 + 4 = 12, nilainya melebihi nilai 9, jadi simpan 1 dan tulis hasilnya 2.\n1+4+1=6\nJadi, hasilnya: 62.\nBilangan biner dijumlahkan dengan cara yang sama dengan penjumlahan bilangan desimal. Dasar penjumlahan untuk masing-masing digit bilangan biner adalah:\n0+0=0\n0+1=1\n1+0=1\n1 + 1 = 0 1 + 1 = 2, karena digit terbesar biner 1, maka harus dikurangi dengan 2\n(basis), jadi 2 - 2 = 0 dengan simpanan 1.\n\n\n\nContoh soal \n1111 = 15\n10100 = 20\n------- + \n100011 = 35\n\natau dengan langkah:\n1 + 0  =1\n1 + 0  =1\n1 + 1 = 0 dengan simpanan 1\n1+1+1 =0\n1+1\t= 0 dengan simpanan 1\nJadi, hasilnya: 1 0 0 0 1 1\n",
    des2: "\n\n\t\t",
  },
  {
    id: "2",
    bab: "Bab 3",
    judul: "A.	Operasi Aritmatika Bilangan Biner",
    des1: "\t\t2.\tPengurangan Bilangan Biner\n\nBilangan biner dikurangkan dengan cara yang sama pada operasi pengurangan bilangan desimal. Dasar pengurangan untuk masing-masing digit bilangan biner adalah:\n0 – 0=0\n1 – 0= 1.\n1 – 1=0\n0- 1 = 1 -> dengan pinjaman 1, (pinjam 1 dan posisi sebelah kirinya).\n\nContoh\n",
    des2: "\n\t\tTabel 3.1. Pengurangan Bilangan Biner",
    des3: "\t\tLangkah-langkah penyelesaiannya :\n1 – 1\t= 0\n1 – 0\t= 1\tJadi hasilnya : 10010\n0 – 0\t= 0\n1 – 1\t= 0\n1 – 0\t= 1\n",
    des4: "\n\t",
    tabel: require("../../src/assets/materi/bab3/3.1.jpg"),
  },
  {
    id: "3",
    bab: "Bab 3",
    judul: "A.	Operasi Aritmatika Bilangan Biner",
    des1: "\t\t3.\tPerkalian Bilangan Biner.\n\nDilakukan sama dengan cara perkalian pada bilangan desimal. Dasar perkalian bilangan biner adalah:\n\n0 x 0\t= 0\n1 x 0\t= 0\n0 x 1\t= 0\n1 x 1\t= 1\n",
    des2: "\n\t\tTabel 3.2. Tabel Perkalian Biner",
    tabel: require("../../src/assets/materi/bab3/3.2.jpg"),
  },
  {
    id: "4",
    bab: "bab 3",
    judul: "A.	Operasi Aritmatika Bilangan Biner",
    des1: "\n\t\t4.\tPembagian Bilangan Biner\n\nPembagian bilangan biner juga dilakukan dengan cara yang sama pada bilangan desimal. Pembagian biner 0 tidak mempunyai arti sehingga dasar pembagian biner adalah\n0 : 1\t= 0\n1 : 1\t= 1\n",
    des2: "\n\t\tTabel 3.3 Pembagian Bilangan Biner",
    tabel: require("../../src/assets/materi/bab3/3.3.jpg"),
  },
  {
    id: "5",
    bab: "bab 3",
    judul: "B.	Operasi Aritmatika Bilangan Oktal",
    des1: "\n\t\t1.\tPenjumlahan Aritmetiha Bilangan Oktal\nPenjumlahan bilangan oktal dapat dilakukan secara sama dengan penjumlahan bilangan desimal.\nLangkah-langkah penjumlahan adalah sebagai berikut.\n1)\tTambahkan masing-masing kolom secara desimal.\n2)\tUbah dan hasil desimal ke oktal.\n3)\tTuliskan hasil dari digit paling kanan dari hasil oktal.\n4)\tJika hasil penjumlahan tiap-tiap kolom terdiri daridua digit, maka digit paling kiri merupakansimpan untuk penjumlahan kolom selanjutnya.\n\nContoh :\n",
    des2: "\n\t\tTabel 3.4. Penjumlahan Bilangan Oktal",
    tabel: require("../../src/assets/materi/bab3/3.4.jpg"),
  },
  {
    id: "6",
    bab: "bab 3",
    judul: "B.	Operasi Aritmatika Bilangan Oktal",
    des1: "\n\t\t2.\tPengurangan Arítmetika Bilangan Oktal\nPengurangan bilangan oktal dapat dilakukan secara sama dengan pengurangan bilangan desimal.\n",
    des2: "\n\t\tTabel 3.6. Pengurangan Bilangan Oktal",
    tabel: require("../../src/assets/materi/bab3/3.5.jpg"),
  },
  {
    id: "7",
    bab: "bab 3",
    judul: "B.	Operasi Aritmatika Bilangan Oktal",
    des1: "\n\t\t3\tPerkalian Aritmetika Bilangan Oktal\nPerkalian bilangan oktal dilakukan dengan cara yang sama pada perkalian bilangan desimal.\nLangkah-langkahnya adalah sebagai berikut.\n1)\tKalikan masing-masing kolom secara desimal.\n2)\tUbah dari hasil desimal ke oktal.\n3)\tTuliskan hasil daridigit paling kanan dan hasil oktal.\n4)\tJika hasil perkalian tiap kolom terdiri dari 2 digit, maka digit paling kiri merupakan simpanan untuk dijumlahkan pada hasil perkalian kolom selanjutnya.\n",
    des2: "\n\t\tTabel 3.7. Pengalian Bilangan Oktal",
    tabel: require("../../src/assets/materi/bab3/3.6.jpg"),
    tabel1: require("../../src/assets/materi/bab3/3.7.jpg"),
  },
  {
    id: "8",
    bab: "bab 3",
    judul: "B.	Operasi Aritmatika Bilangan Oktal",
    des1: "\n\t\t4.\tPembagian Aritmetika bilangan Oktal",
    des2: "\n\t\tTabel 3.8.Pembagian bilangan Oktal",
    tabel: require("../../src/assets/materi/bab3/3.8.jpg"),
  },
  {
    id: "9",
    bab: "bab 3",
    judul: "C.	Operasi Aritmatika Bilangan Heksadesimal",
    des1: "\n\t\t1.\tPenjumlahan Operasi Aritmetika Bilangan Heksadesimal\n\nPenjumlahan bilangan heksadesimal dapat dilakukan secara sama dengan penjumlahan bilangan oktal.Langkah-Iangkah penjumlahan bilangan heksadesimal adalah sebagai berikut.\n1)\tTambahkan masing-masing kolom secara desimal.\n2)\tUbah dari hasil desimal ke heksadesimal.\n3)\tTuliskan hasil dari digit paling kanan dari hasil heksadesimal.\n4)\tJika hasil penjumlahan tiap-tiap kolom terdiri daridua digit, maka digit paling kiri merupakansimpanan untuk penjumlahan kolom selanjutnya.\n",
    des2: "\n\t\tTabel 3.9. Penjumlahan Bilangan Heksadesimal",
    tabel: require("../../src/assets/materi/bab3/3.9.jpg"),
  },
  {
    id: "10",
    bab: "bab 3",
    judul: "C.	Operasi Aritmatika Bilangan Heksadesimal",
    des1: "\n\t\t2.\tPengurangan Operasi Aritmetika Bilangan Heksadesimal\n\nPengurangan bilangan heksadesimal dapat dilakukan secara sama dengan pengurangan bilangan desimal.\n",
    des2: "\n\t\tTabel 3.10.Pengurangan Bilangan Heksadesimal",
    tabel: require("../../src/assets/materi/bab3/3.10.jpg"),
  },
  {
    id: "11",
    bab: "bab 3",
    judul: "C.	Operasi Aritmatika Bilangan Heksadesimal",
    des1: "\n\t\t3.\tPerkalian Operasi Aritmetika Bilangan Heksadesimal\nPerkalian bilangan heksadesimal dapat dilakukan secara sama dengan perkalian bilangan desimal, dengan langkah-Langkah sebagai berikut.\n1)\tKalikan masing-masing kolom secara desimal.\n2)\tUbah dari hasil desimal ke oktal.\n3)\tTuliskan hasil dari digit paling kanan dari hasil oktal.\n4)\tJika hasil perkalian tiap kolom terdiri dari 2 digit, maka digit paling kiri merupakan simpanan untuk dijumlahkan pada hasil perkalian kolom selanjutnya.\n",
    des2: "\n\t\tTabel 3.11.Perkalian Bilangan Heksadesimal",
    tabel: require("../../src/assets/materi/bab3/3.11.jpg"),
  },
  {
    id: "12",
    bab: "bab 3",
    judul: "C.	Operasi Aritmatika Bilangan Heksadesimal",
    des1: "\n\t\t4.\tPembagian Operasi Aritmetika Bilangan Heksadesimal\nPembagian bilangan heksadesimal dapat dilakukan secara sama dengan pembagian bilangandesimal.\n",
    des2: "\n\t\tTabel 3.12.Pembagian Bilangan Heksadesimal",
    tabel: require("../../src/assets/materi/bab3/3.12.jpg"),
  },
  // {
  //   id: "13",
  //   bab: "bab 3",
  //   judul: "Konversi Bilangan Biner ke Sistem Bilangan Oktal",
  //   des1:"\n\t\tKonversi dari bilangan biner ke bilangan oktal dapat dilakukan dengan mengkonversikan tiap- tiap tiga buah digit biner. Misalnya, bilangan biner 11010100 dapat dikonversikan ke oktal dengan cara :\n\n11 / 3\t\t 010 / 2\t\t100 / 4\n\nHubungan ini dapat dilihat pada tabel dibawah ini.\n",
  //   des2:"\n\t\tTabel 1.7 Konversi Bilangan Oktal",
  //   image: require("../../src/assets/book.png"),
  //   tabel:require("../../src/assets/materi/bintooctal.jpg"),
  // },
  // {
  //   id: "14",
  //   bab: "bab 3",
  //   judul: "Konversi Bilangan Biner ke Sistem Bilangan Heksadesimal",
  //   des1:"\n\t\tKonversi dari bilangan biner ke bilangan heksadesimal dapat dilakukan dengan mengkonversikan tiap-tiap empat buah digit biner.Misalnya bilangan biner 11010100 dapat dikonversikan ke bilangan heksadesimal dengan cara\n\n1101/D\t\t 0100/4\n\nHubungan ini dapat dilihat pada tabel berikut.\n",
  //   des2:"\n\t\tTabel 1.8 Konversi bit bilangan Heksadesimal",
  //   image: require("../../src/assets/book.png"),
  //   tabel:require("../../src/assets/materi/bintoheksa.jpg"),
  // },
  // {
  //   id: "15",
  //   bab: "bab 3",
  //   judul: "Konversi Bilangan Oktal ke Sistem Bilangan Desimal",
  //   des1:"\n\t\tBilangan oktal dapat dikonversikan ke bilangan desimal dengan cara mengalikan masing-masing bit dalam bilangan dengan nilai tempatnya.",
  //   des2:"\n\n\t\t",
  //   image: require("../../src/assets/book.png"),
  //   tabel:require("../../src/assets/materi/octaltodes.jpg"),
  // },
  // {
  //   id: "16",
  //   bab: "bab 3",
  //   judul: "Konversi Bilangan Oktal ke Sistem Bilangan Biner",
  //   des1:"\n\t\tKonversi dan bilangan oktal ke bilangan biner dapat dilakukan dengan mengkonversikanmasing-masing digit oktal ke 3 digit biner, sebagai berikut.",
  //   des2:"\n\t\t",
  //   des3:"\n\n\n\t\t",
  //   image: require("../../src/assets/book.png"),
  //   tabel:require("../../src/assets/materi/octaltobiner.jpg"),
  // },
  // {
  //   id: "17",
  //   bab: "bab 3",
  //   judul: "Konversi Bilangan Oktal ke Sistem Bilangan Heksadesimal",
  //   des1:"\n\t\tKonversi dan bilangan oktal ke bilangan heksadesimal dapat dilakukan dengan cara mengubah dari bilangan oktal menjadi bilangan biner terlebih dahulu, kemudian dikonversikan kebilanganheksadesimal. Misalnya, bilangan oktal 2537, akan dikonversikan ke heksadesimal, dengan langkah-langkahberikut ini.",
  //   image: require("../../src/assets/book.png"),
  //   tabel:require("../../src/assets/materi/octaltoheksa.jpg"),
  // },
  // {
  //   id: "18",
  //   bab: "bab 3",
  //   judul: "Konversi Bilangan Heksadesimal ke Sistem Bilangan Desimal",
  //   des1:"\n\t\tDari bilangan heksadesimal dapat dikonversikan ke bilangan desimal dengan cara mengalikanmasing-masing digit bilangan dengan nilai tempatnya.",
  //   des2:"\n\t\t",
  //   des3:"\n\t\tUntuk mengkonversikan bilangan heksadesimal ke bilangan desimal, dapat dengan bantuan table berikut.\n\nTabel 1.9 Hubungan nilai heksadesimal di posisi tertentu dengan nilai desimal",
  //   image: require("../../src/assets/book.png"),
  //   tabel:require("../../src/assets/materi/heksatodes.jpg"),
  //   tabel1:require("../../src/assets/materi/heksatodes1.jpg"),
  // },
  // {
  //   id: "19",
  //   bab: "bab 3",
  //   judul:"Konversi Bilangan Heksadesimal ke Sistem Bilangan Biner",
  //   des1:"\n\t\tKonversi dan hilangan heksadesimal ke sistem bilangan biner dapat dilakukan denganmengkonversikan masing-masing digit heksadesimal ke 4 digit biner sebagai berikut.",
  //   des2:"\n\t\t",
  //   image: require("../../src/assets/book.png"),
  //   tabel:require("../../src/assets/materi/heksatobiner.jpg"),
  // },
  // {
  //   id: "20",
  //   bab: "bab 3",
  //   judul:"Konversi Bilangan Heksadesimal ke Sistem Bilangan Oktal",
  //   des1:"\n\t\tKonversi dan bilangan heksadesimal ke bilangan oktal dapat dilakukan dengan cara mengubah dari bilangan heksadesimal menjadi bilangan biner terlebih dahulu, baru dikonversikan ke bilangan oktal.Misalnya bilangan heksadesimal 55F, akan dikonversikan ke oktal dengan Iangkah-Iangkah:",
  //   des2:"\n\t\t",
  //   image: require("../../src/assets/book.png"),
  //   tabel:require("../../src/assets/materi/heksatooctal.jpg"),
  // },
  // {
  //   id: "21",
  //   bab: "bab 3",
  //   judul: "Bentuk BCD ( Binary Coded Decimal)",
  //   des1:"\n\t\tBCD merupakan sistem sandi dengan 6 bit, sehingga kombinasi yang dapat digunakan sebagai sandi banyaknya adalah 2 pangkat 6 sama dengan 64 kombinasi. Pada transmisi sinkron sebuah karakter dibutuhkan 9 bit, yang terdiri dari 1 bit awal, 6 bit data, 1 bit paritas dan 1 bit akhir. (Kristanto, 2003, hal. 97)\n\n\t\tBCD (Binary Coded Decimal) merupakan kode biner yang digunakan hanya untuk mewakili nilai digit desimal saja, yaitu nilai angka 0 sampai dengan 9. BCD menggunakan kombinasi dari 4 bit, sehingga sebanyak 16 (24 = 16) kemungkinan kombinasi yang bisa diperoleh dan hanya 10 kombinasi yang digunakan.\n",
  //   des2:"\n\t\tTabel 1.10 BCD 4-bit",
  //   des3:"\n\t\tBilangan desimal pada setiap tempat dapat terdiri dari 10 bilangan yang berbeda- beda. Untuk bilangan biner, bentuk dari 10 elemen yang berbeda-beda memerlukan 4 bit. Sebuah BCD mempunyai 4 bit biner untuk setiap tempat bilangan desimal.",
  //   des4:"\n\t\tDalam contoh ini BCD terdiri dan 3 kelompok bilangan masing-masing terdiri dari 4 bit, dan jika bilangan desimal tersebut dikonversi ke dalam bilangan biner secara langsung adalah 31710 = 1001111012 dan hanya memerlukan 9 bit. Untuk contoh proses sebaliknya dapat dilihat di bawah ini.",
  //   image: require("../../src/assets/book.png"),
  //   tabel:require("../../src/assets/materi/bcd.jpg"),
  //   tabel1:require("../../src/assets/materi/bcd1.jpg"),
  //   tabel2:require("../../src/assets/materi/bcd2.jpg"),
  // },
  // {
  //   id: "22",
  //   bab: "bab 3",
  //   judul:"Bentuk BCH ( Binary Coded Hexadecimal)",
  //   des1:"\n\t\tBilangan heksadesimal dalam setiap tempat dapat terdiri dari 16 bilangan yang berbeda-beda angka dan huruf. Bentuk biner untuk 16 elemen memerlukan 4 bit.",
  //   des2:"\n\t\tTabel 1.11 BCH",
  //   des3:"\t\tSebuah BCH mempunyai 4 bit biner untuk setiap tempat bilangan heksadesimal.",
  //   image: require("../../src/assets/book.png"),
  //   tabel:require("../../src/assets/materi/bch.jpg"),
  //   tabel1:require("../../src/assets/materi/bch1.jpg"),
  // },
  // {
  //   id: "23",
  //   bab: "bab 3",
  //   judul:"ASCII Code-American Standard Code-for Information Interchange",
  //   des1:"\n\t\tDalam bidang komputer mikro, ASCII Code mempunyai arti yang sangat khusus, yaitu untuk mengkodekan karakter (huruf, angka, dan tanda baca yang Iainnya). Kode- kode ini merupakan kode standar yang dipakai oleh sebagian besar sistem komputer mikro. Selain huruf, angka dan tanda baca yang terdiri dari 32 karakter (contoh: ACK, NAK), ASCII Code merupakan kontrol untuk keperluan transportasi data. Di bawah ini adalah tabel 7 bit ASCII Code beserta beberapa penjelasan yang diperlukan.",
  //   des2:"\n\t\tTabel 1.12ACII Code 7 bit",
  //   des3:"\t\tASCII merupakan sandi 7 bit, sehingga terdapat 2 pangkat 7 yang berarti ada 128 macam simbol yang dapat disandikan dengan sistem sandi ini, sedangkan bit ke 8 merupakan bit paritas. Sandi ini dapat dikatakan yang paling banyak dipakai sebagai standard pensinyalan pada peralatan komunikasi data. Untuk transmisi asinkron tiap karakter disandikan dalam 10 atau 11 bit yang terdiri dari 1 bit awal, 7 bit data, 1 bit paritas, 1 atau 2 bit akhir.\n\nTabel 1.13 Sandi ASCII",
  //   image: require("../../src/assets/book.png"),
  //   tabel:require("../../src/assets/materi/ascii.jpg"),
  //   tabel1:require("../../src/assets/materi/ascii2.jpg"),
  // },
];

export default materitiga;
