const materilima = [
  {
    id: "1",
    bab: "Bab 5",
    judul: "Multiplexer dan Decoder ",
    des1: "\t\tA.\tMultiplexer\nFungsi multiplexer adalah memilih 1 dan N (sumber) data masukan dan meneruskan data yang dipilih itu kepada suatu saluran informasi tunggal. Di dalam multiplexer hanya terdapat satu jalan masuk dan mengeluarkan data-data yang masuk kepada salah satu dan N saluran keluar, maka suatu multiplexer sebenamya melaksanakan proses kebalikan dari demultiplexer. Gambar berikut merupakan suatu multiplexer 4 ke 1 saluran. Perhatikan bahwa konfigurasi pendekodean yang sama digunakan, baik dalam multiplexer maupun dalam demultiplexer.\n",
    des2:"",
    tabel: require("../../src/assets/materi/bab5/5.1.jpg"),
  },
  {
    id: "2",
    bab: "Bab 5",
    judul: "Multiplexer dan Decoder",
    des1: "\t\tB.\tDemultiplexer\nDemultiplexer adalah suatu sistem yang menyalurkan sinyal biner (data serial) pada salah satu dari n (saluran) yang tersedia, Suatu pendekode dapat diubah menjadi demultiplexer seperti dijelaskan pada Gambar 5.2.\n",
    tabel:require("../../src/assets/materi/bab5/5.2.jpg"),
  },
  {
    id: "3",
    bab: "Bab 5",
    judul: "Multiplexer dan Decoder",
    des1: "\t\tC.\tDecoder\nDecoder berfungsi untuk mengidentifikasi atau mengenali suatu kode tertentu.\nDalam suatu sistem digital perintah-perintah ataupun bilangan-bilangan dikirim dengan deretan denyut (pulsa) atau tingkatan-tingkatan biner. Misalnya, jika kita menyediakan karakter 4 bit untukpengiriman instruksi, maka jumlah instruksi berbeda yang dapat dibuat adalah 24=16. lnformasi ini diberi kode atau sandi biner. Di pihak lain, seringkali timbul kebutuhan akan suatu sakelarmultiposisi yang dapat dioperasikan sesuai dengan kode tersebut. Dengan kata lain, untuk masing-masing dan 16 saluran hanya 1 saluran yang penambahan pada setiap saat.\nProses untuk identifikasi suatu kode tertentu ini disebut pendekodean atau decoding. Sistem BCD (Binary Coded Decimal) menerjemahkan bilangan—bilangan desimal dengan menggantikan setiap digit desimal menjadi 4 bit biner. 4 digit biner dapat dibuat 16 kombinasi, maka 10 di antaranya dapat digunakan untuk menyatakan digit desimal 0 sampai 9. Dengan ini kita memiliki pilihan kode BCD yang luas. Salah satu pilihan yang disebut kode 8421. Contohnya, bilangan desimal 264 memerlukan 3 gugus yang masing- masing terdiri dari 4 bit biner yang berturut-turut dari khi (MSB) ke kanan (ISB) sebagai berikut: 0010 0110 0100 (BCD).\nPerhatikan gambar, keluaran gerbang AND 1 jika masukan BCD adaLah 0101 dan sama dengan untuk instruksi masukan yang lain. Karena kode ini merupakan representasi bilangan desimal 5 maka keluaran ini dinamakan saluran atau jalur 5. Keluaran decoder ini harus dihubungkan dengan peralatan yang dapat dibaca dan dimengerti manusia.\n\nJenis-Jenis Rangkaian Decoder\n1)\tBCD ke 7segment Decoder\n",
    des2:"\n\t\t",
    des3:"\t\tKombinasi masukan biner dan jalan masukan akan diterjemahkan oleh decoder sehinggamembentuk kombinasi nyala LED peraga (7 segment LED) sesuai dengan kombinasi masukan biner tersebut. Sebagai contoh, jika masukan biner DCBA = 0001, maka decoder akan memilih jalur keluaran mana yang akan diaktifkan. Dalam hal ini\n \nsaluran b dan c diaktifkan sehingga lampu LED b dan C menyala dan menandakan angka 1.\n\n2)\tDecoder BCD ke Desimal\nKeluarannya dihubungkan dengan tabung indicator angka sehingga kombinasi angka biner akan menghidupkan lampu indikator angka yang sesuai. Contohnya, D = C\n= B =0, A= 1, akan menghidupkan lampu indikator angka 1. Lampu indikator yang menyala akan sesuai dengan angka biner dalam jalan masuk.\n",
    tabel:require('../../src/assets/materi/bab5/5.3.jpg'),
    tabel1:require('../../src/assets/materi/bab5/5.4.jpg'),
  },
  {
    id: "4",
    bab: "bab 5",
    judul: "Multiplexer dan Decoder",
    des1:"\n\t\tD.\tEncoder\nEncoder  adalah  kebalikan  dari  proses  decoder  di  mana  suatu  pengkode  atau\nencoder memiliki sejumlah masukan. Pada saat tertentu hanya salah satu dan masukan- masukan itu yang berada pada keluaran 1 dan sebagai akibatnya suatu kode N bit akan dihasilkan sesuaidengan masukan khusus yang ditambahkan. Misalnya, kita ingin menyalurkan suatu kode biner untuk setiappenekanan tombol pada keyboard alpha numeric (suatu mesin tik atau tele type). Pada keyboard tersebut terdapat26 huruf kecil,\n10 angka dan sekitar 22 huruf khusussehingga kode yang diperlukan lebih kurang berjumlah 84. Syarat ini bisa dipenuhi dengan jumlah bit minimum\nsebanyak 7 (2=128), Kini misalkan bahwa keyboard D C Btersebut diubah sehingga setiap saat suatu tombol ditekan, sakelar yang bersangkutan akan menutup. Dandengan\n \ndemikian menghubungkan suatu catu daya 5 voIt (bersesuaian dengan keadaan1) dengan saluran masuk tertentu. Diagram skema rangkaian encoder ditunjukkan pada\n",
    des2:"\n\t\t",
    des3:"\n\t\tEncoder merupakan rangkaian penyandi dari bilangan dasar (desimal) menjadi kode biner(BCD). Bila tombol 1 ditekan, maka D1 akan on menghubungkan jalur A ke logika 0 (GND),akibatnya pada NOT gate 1 timbul keluaran 1 sehingga timbul kombinasi logika biner 0001, dan seterusnya.\nRangkaian encoder juga dapat disusun dengan menggunakan gerbang NAND sebagai berikut.\n",
    des4:"\n\t\tTabel kebenaran dari rangkaian encoder decimal ke BCD dengan diode logika dan gerbang NAND sebagai berikut.",
    tabel:require("../../src/assets/materi/bab5/5.5.jpg"),
    tabel1:require("../../src/assets/materi/bab5/5.6.jpg"),
    tabel2:require("../../src/assets/materi/bab5/5.7.jpg"),
  },
  {
    id: "5",
    bab: "bab 5",
    judul: "Rangkaian Flip-Flop ( RS, JK, D )",
    des1:"\n\t\tA.\tRS Flip-Flop\nRS Flip-Flop adalah rangkaian flip-flop yang mempunyai 2 jalan keluaran (Q).\nSimbol-simbolyang ada Pada jalan keluar selalu berlawanan satu dengan yang lain. RS- FF adalah flip-flop dasar yang memiliki dua masukan, yaitu R (Reset) dan S (Set). Bila S diberi logika 1 dan R diberi logika 0, maka output Q akan berada pada logika 0 dan Q pada logika 1. Bila R diberi logika 1 dan S diberi logika 0, maka keadaan output akan berubah menjadi Q berada pada logika 1 dan Qnot pada logika 0.\nSifat paling penting dari flip-flop adalah sistem ini dapat menempati salah satu dari dua keadaanstabil, yaitu stabil I diperoleh saat Q = 1 dan Q01 = O, stabil ke Il diperoleh saat Q = O dan Q, = 1 yang diperlihatkan pada Gambar\n",
    des2:"\n\t\t",
    des6:"\n\t\tYang dimaksud dengan kondisi terlarang adalah keadaaan yang tidak diperbolehkan, yaitukondisi output Q sama dengan Q pada saat S = 0 dan R = 0. Yang dimaksud dengan kondisimemori adalah saat S = 1 dan R = 1, output Q dan Q akan menghasilkan perbedaan, yaitu jikaQ = 0 maka Q = 1 atau sebaliknya jika Q = 1 maka Q\n= 0.\n",
    tabel:require("../../src/assets/materi/bab5/5.8.jpg"),
    tabel1:require("../../src/assets/materi/bab5/5.9.jpg"),
  },
  {
    id: "6",
    bab: "bab 5",
    judul: "Rangkaian Flip-Flop ( RS, JK, D )",
    des1:"\n\t\tB.\tJ-K Flip-Flop\nJK flip-flop sering disebut dengan JK FF atauMaster Slave JK FF karena terdiri\ndari dua buah flip- flop, yaitu Master FF dan Slave FE Master Slave JK FF ini memiliki 3 buah terminal input, yaitu J, K, JK i+ Q dan Clock. IC yang dipakai untuk menyusun JK FF adalah upe 7473 yang mempunyal 2 buah JR flip-flop di mana lay outnya dapat dilihat pada Vodemaccum IC (Data book 1C). Kelebihan JK FF terhadap FF sebelumnya yaitu JK FF tidak mempunyai kondisi terlarang artinya berapa pun input yang diberikan asal ada jam sistem maka akan terjadi perubahan pada output.\n",
    tabel:require("../../src/assets/materi/bab5/5.10.jpg"),
  },
  {
    id: "7",
    bab: "bab 5",
    judul: "Rangkaian Flip-Flop ( RS, JK, D )",
    des1:"\n\t\tC.\tD Flip-Flop\nD flip-flop adalah RS flip-flop yang ditambah dengan suatu inventer pada reset\ninputnya. Sifat dan D flip-flop adalah bila input D (Data) dan denyut jam sistem (pulse clock) bemilal 1, maka output Q akan bernilai 1 dan bila input D bernilai 0, maka D flip- flop akan berada pada keadaanreset atau output Q hemilai 0.\n",
    tabel:require("../../src/assets/materi/bab5/5.11.jpg"),
  },
  {
    id: "8",
    bab: "bab 5",
    judul: "Rangkaian Flip-Flop ( RS, JK, D )",
    des1:"\n\t\tD.\tCRS Flip- Flop\nCR5 flip-flop adalah clocked RS-FF yang dilengkapi dengan sebuah terminal denyut jam sistem.Denyut Jam sistem ini berfungsi mengatur keadaan Set dan Reset. Bila denyut jam sistem bernilai 0,maka perubahan nilai pada input R dan S tidak akan mengakibatkan perubahan pada output Q dan Qnot. Akan tetapi, apabila denyut jam istem bernilai 1, maka perubahan pada input R dan S dapat mengakibatkan perubahan pada output Q dan Qnot.\n",
    tabel:require("../../src/assets/materi/bab5/5.12.jpg"),
  },
  {
    id: "9",
    bab: "bab 5",
    judul: "Rangkaian Flip-Flop ( RS, JK, D )",
    des1:"\n\t\tE.\tT Flip-Flop\nRangkaian T flip-flop atau Toggle flip-flop (TFF) dapat dibentuk dari modifikasi\nclocked RSFF,DFF maupun JKFE TFF mempunyai sebuah terminal input T dan dua buah terminal output Qdan Qnot. TFF banyak digunakan pada rangkaian Counter, pembagi frekuensi dan sebagainya.\n",
    tabel:require("../../src/assets/materi/bab5/5.13.jpg"),
  },
];

export default materilima;
