const materi = [
  {
    id: "1",
    bab: "Bab 1",
    judul: "Pengertian Sistem Komputer",
    des1: "\t\tSistem bilangan adalah suatu cara untuk mewakili besaran dari suatu item fisik. Sistem bilangan menggunakan basis ( base/ radix ) tertentu yang tergantung dari jumlah bilangan yang di gunakan. Konsep dasar sistem bilangan, senantiasa mempunyai Base (radix), absolute digit dan positional (place) value\n",
    des2:"\t\tUntuk memudahkan mempelajari komputer sebagai pengolah data, kita harus memandangnya sebagai sebuah sistem komputer (computer system). Secara umum, Sistem komputer adalah jaringan elemen-elemen yang saling berhubungan, berbentuk satu kesatuan untuk melaksanakan suatu tujuan pokok dan sistem tersebut.\n",
    des3:"\t\tTujuan pokok dan sistem komputer adalah mengolah data untuk menghasilkan informasi. Supaya tujuan pokok tersebut tercapai, maka  harus  ada  elemen-elemen yang mendukungnya. Elemen-elemen dan sistem komputer adalah hardware, software, dan brainware.\n",
    des4:"\t\t1.\tHardware (perangkat keras) adalah peralatan di sistem komputer yang secara fisik terlihat dan dapat dijamah, seperti monitor, keyboard, dan mouse.\n\t\t2.\tSoftware (perangkat lunak) adalah program yang berisi perintah-perintah untuk melakukan pengolahan data. Ada tiga bagian utama dan software :\n\t\t\ta.\tSistem operasi : DOS, Linux, Windows, dan Mac.\n\t\t\tb.\tBahasa pemrograman : Visual Basic, C++, Pascal, Java, dan Visual C.\n\t\t\tc.\tAplikasi : MS Office, Antivirus, Winamp, dan Mozilla.\n\t\t3.\tBrainware adalah manusia yang terlibat dalam mengoperasikan serta mengatur sistem komputer.\n",
    des5:"\t\tKetiga elemen sistem komputer tersebut harus saling berhubungan dan membentuk satu-kesatuan. Hardware tanpa adanya software maka tidak akan berfungsi seperti yang diharapkan, hanya berupa benda mati saja. Software yang akan mengoperasikan hardwarenya. Hardware yang sudah didukung oleh software juga tidak akan berfungsi jika tidak ada manusia yang mengoperasikamya.",
    image: require("../../src/assets/book.png"),
    video:"eQZzRbAXct8",
  },
  {
    id: "2",
    bab: "Bab 1",
    judul: "Kemampuan Komputer",
    des1: "\t\tKemampuan komputer yang paling menakjubkan adalah kecepatannya. Komputer dapat melakukan operasi dasar seperti penjumlahan atau pengurangan dalam waktu yang sangat cepat, yaitu dalam satuan millisecond, nanosecond, atau picosecond. Komputer yang paling cepat dapat melakukan operasi dalam waktu picosecond.\n\t\tKemampuan komputer lainnya adalah kapasitas memori, yakni kemampuan penyimpanan data dan komputer. Satuan memori komputer dinyatakan dengan byte. Untuk memahami pengertian byte, kita bisa melihatnya di Tabel 1.1 berikut ini.\n",
    des2:"\n\t\tTabel 1.1. Satuan Kapasitas Memori Komputer",
    des3:"\t\tSering kali orang membandingkan komputer dengan manusia. Tentunya ada beberapa kelebihan dan kekurangan dari keduanya. Jadi, sebenarnya penggunaan komputer tidak seluruhnya menggantikan fungsi kerja dan manusia, tetapi hanya sebagai alat bantu saja. Komputer merupakan perkembangan teknologi yang penting karena meningkatkan kemampuan daya manusia.",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/memorikom.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "3",
    bab: "Bab 1",
    judul: "Siklus Pengolahan Data",
    des1: "\t\tSuatu proses pengolahan data terdiri dan 3 tahapan dasar yang disebut dengan siklus pengolahan data (data processing cycle), yaitu input, processing. dan output. Diagram dan siklus pengolahan data ini dapat dilihat di Gambar 1.1 berikut ini.\n",
    des2:"\n\t\tGambar 1.1 Siklus Pengolahan Data",
    des3:"\t\tInput adalah masukan, yang dalam hal ini berupa data-data yang dimasukkan (di- input) ke dalam komputer. Input bisa berupa pengetikan huruf, pemindaian (scanning) gambar, scanning barcode, scanning kartu magnetik atau RFID, hasil foto, suara / rekaman, dan lain-lain. Processing adalah pengolahan data itu sendiri, yang dilakukan oleh sistem komputer. Output adalah keluaran yang disajikan oleh komputer. Output ini dapat berupa tampilan di layar monitor, hasil cetak, file data di media penyimpan (harddisk/Flashdisk atau cakram).\n\t\t( Heriyanto, dkk, 2014, hal 2 ) Dalam gambar Siklus Pengolahan data secara global terdiri dari tiga blok yaitu blok masukan (input), blok proses, dan blok keluaran (output). Fungsi dari masing-masing blok dapat dijelaskan sebagai berikut.\n",
    des4:"\n\t\t\ta.\tBlok Input.\n\t\t\t\t\tBagian blok ini merupakan pintu masuk dari sistem komputer yang berfungsi untuk menerima seluruh aktifitas masukan dari pengguna secara langsung maupun tidak langsung (dapat berupa peralatan atau mesin yang lain diluar sistem).\n\n\t\t\tb.\tBlok Proses.\n\t\t\t\t\tBagian blok ini merupakan pusat aktifitas proses pengolahan dari berbagai data masukan yang diberikan oleh pengguna sesuai dengan ketentuan yang telah ditetapkan sebelumnya sehingga mampu memberikan hasil yang sesuai dengan keinginan pengguna. Selanjutnya hasil proses akan disalurkan ke pengguna secara langsung atau tidak langsung melalui blok output. Proses yang dilakukan oleh bagian ini sebagian besar merupakan hasil perhitungan maupun logika secara digital dalam bentuk besaran- besaran listrik dalam rangkaian elektronik yang sangat kompleks. Besaran-besaran listrik digital ini selanjutnya digambarkan sebagai kode bilangan biner maupun heksa desimal. Kode-kode inilah yang selanjutnya menjadi kode perintah bagi mesin pemroses ini untuk menjalankan seluruh perintah yang diberikan kepadanya. Kode perintah ini juga dikenal sebagai bahasa mesin (machine language). Jadi pada bagian blok proses hanya dapat menjalankan   pengolahan   data  sesuai  dengan\tperintah-perintah yang diberikan kepadanya.\n\n\t\t\tc.\tBlok Output.\n\t\t\t\t\tPada bagian ini merupakan perantara yang menjembatani antara blok proses dengan pengguna untuk melihat atau mengambil hasil proses.\n",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/siklus.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "4",
    bab: "bab 1",
    judul: "Sistem Bilangan Desimal",
    des1:"\n\t\tSistem bilangan desimal menggunakan 10 macam simbol bilangan berbentuk 10 digit angka, yaitu 0, 1 , 2, 3, 4, 5, 6, 7, 8 dan 9. Sistem bilangan desimal menggunakan basis atau radiks 10 . Bentuk nilai suatu bilangan desimal dapat berupa integer desimal (decimal integer) atau pecahan desimal (fraction decimal). Integer desimal adalah nilai desimal yang bulat, misalnya nilai 8598. Yang dapat diartikan.\n8  x 103 =  8000\n5  x 102 =  500\n9  x 101 =  90\n8  x 100 =  8\n                +\n8598\n\nAbsolut value merupakan nilai muilak dari masing-masing digit di bilangan. position value (nilai tempat) merupakan penimbang atau bobot dan masing-masing digit bergantung pada posisinya,yaitu bemilai basis dipangkatkan dengan urutan posisinya.",
    des2:"\n\t\tTabel 1.2. Bilangan Desimal",
    des3:"\n\t\tOleh karena itu, nilai 8598 dapat juga diartikan dengan (8 X 1000) + (5 X 100) + (9 x 10) + (8 x 1). Pecahan desimal adalah nilai desimal yang mengandung nilai pecahan di belakang koma, misalnya nilal 183,75 adalah pecahan desimal yang dapat diartikan:\n1 x 102 = 100\n8 x 101 = 80\n3 x 100 = 3\n7 x 10-1 = 0,7\n5 x 10-2 = 0,05\n              +\n183,75\n\n\t\tBaik integer desimal maupun pecahan desimal dapat ditulis dengan bentuk eksponensial. Misalnya nilai 82,15 dapat dituliskan 0,8215 X 102. Setiap nilai desimal yang bukan nol dapat dituliskan dalam bentuk eksponensial standar (standard exponential form), yaitu ditulis dengan mantissa dan eksponen. Mantissa merupakan nilai pecahan yang digit pertama di belakang koma bukan beniilai nol.\n",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/bildes.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "5",
    bab: "bab 1",
    judul: "Sistem Bilangan Biner",
    des1:"\n\t\tBilangan biner adalah bilangan yang berbasis 2 yang hanya mempunyai 2 digit yaitu\n0 dan 1. 0 dan 1 disebut sebagai bilangan binary digit atau bit. Bilangan biner ini digunakan sebagai dasar kompetensi digital. Bobot faktor untuk bilangan biner adalah pangkat / kelipatan 2.\n \nSistem bilangan biner menggunakan 2 macam simbol bilangan berbentuk 2 digit angka, yaitu 0 dan 1. Sistem bilangan biner menggunakan basis 2 .\n\nNilai tempat sistem bilangan biner merupakan perpangkatan dan nilai 2 sebagai berikut.\n",
    des2:"\n\t\tTabel 1.3 Bilangan Biner",
    des3:"\n\t\tContoh Soal\n1.\tberapakah nilai bilangan desimal dan bilangan bilangan biner berikut ini. a. 10012\t=\t10\nb. 1011012\t=\t10\nc. 111001102  =\t10\n\nPenyelesaian:\na. 1001=\n8\t4\t2\t1\n1\t0\t0\t1\n\nMaka : 8 + 1 = 910\natau\n10012\t= 20 + 21\n= 1 + 8\n= 9 10\nb. 1011012\t= a5 x 25 + a4 x 24 + a3 x 23 + a2 x 22 + a1 + a0\n= 1 x 32+0 x 16 +1 x 8 + 1 x 4 + 0 x 2 + 1\n= 32 + 0 + 8 + 4 + 0 + 1\n= 45 10\n\nc. 111001102=\n\n128\t64\t32\t16\t8\t4\t2\t1\n1\t1\t1\t0\t0\t1\t1\t0\n111001102\t= 128 + 64 + 32 + 4 + 2\n= 23410\n",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/bilbiner.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "6",
    bab: "bab 1",
    judul: "Sistem Bilangan Octal",
    des1:"\n\t\tSistem bilangan oktal (octal number system) menggunakan 8 macam simbol bilangan, yaitu 0, 1, 2, 3, 4, 5, 6, 7. Sistem bilangan oktal menggunakan basis 8 . Nilai tempat sistem bilangan oktal merupakan perpangkatan dari nilai 8 sebagai berikut.",
    des2:"\n\t\tTabel 1.4 Bilangan Oktal",
    des3:"\n\t\tMisalnya bilangan oktal 1213 di dalam sistem bilangan desimal bernilai 1 x 83 + 2 x 82 + 1 x 81 + 3 x 80 = 1 x 512 + 2 x 64 + 1 x 8 + 3 x 1 = 512 + 128 + 8 + 3 = 651 atau ditulis\ndengan notasi: 12138 = 65110\n",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/biloctal.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "7",
    bab: "bab 1",
    judul: "Sistem Bilangan Heksadesimal",
    des1:"\n\t\tSistem bilangan heksadesimal (hexadecimal number system) menggunakan 16 macam simbol, yaltu 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C. D, E, dan F. Sistem bilangan heksadesimal menggunakan basis 16. Sistem bilangan heksadesimal digunakan untuk alasan-alasan tertentu di beberapa komputer, misalnya IBM System/360, Data General Nova, PDP — 1 1 DEC,\nHoneywell, beberapa komputer mini dan beberapa komputer mikro. Sistem bilangan heksadesimal mengorganisasikan memori utama ke dalam suatu byte yang terdiri dari 8 bit (binary digit). Masing-masing byte digunakan untuk menyimpan satu karakter alfanumerik yang dibagi dalam dua grup masing-masing bagian 4 bit. Bila satu byte dibentuk dari dua grup 4 bit, masing-masing bagian 4 bit disebut dengan nibble. 4 bit pertama disebut dengan high-ordernibble dan 4 bit kedua disebut dengan low-order nibble.\n\nBila komputer menangani bilangan dalam bentuk biner yang diorganisasikan dalam bentuk grup 4 bit, akan lebih memudahkan untuk menggunakan suatu simbol yang mewakili sekaligus 4 digit biner tersebut. Kombinasi dari 4 bit akan didapatkan sebanyak\n16 kemungkinan kombinasi yang dapat diwakili sehingga dibutuhkan suatu sistem bilangan yang terdiri dari 16 macam simbol atau yang berbasis 1, yaitu sistem bilangan heksadesimal. Digit 0 sampai dengan 9 tidak mencukupi, maka huruf A, B, C, D, E dan F dipergunakan. Misalnya bilangan biner 11000111 dapat diwakili dengan bilangan heksadesimal menjadi C7.\n\nNilai hexadesimal C7 tersebut dalam sistem bilangan desimal bemilai: C716\t= C X 161 + 7 x 160\n= 12 X 16 + 7 X 1\n= 192 + 7\n= 19910\n \nNilai tempat sistem bilangan heksadesimal merupakan perpangkatan dari nilai 16, seperti ditunjukkan pada table berikut.\n",
    des2:"\n\t\tTabel 1.5 Bilangan Heksadesimal",
    des3:"\n\t\t",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/bilheksa.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "8",
    bab: "bab 1",
    judul: "Konversi Bilangan",
    des1:"\n\t\tAngka - angka pada setiap sistem bilangan dapat dikonversikan ke dalam sistem bilangan lain. Dalam melakukan pengkonversian diperlukan ketelitian, ketekunan, dan kecermatan. Perhatikan tabel konversi decimal, biner, octal dan hexadecimal berikut ini dengan seksama.",
    des2:"\n\t\tTabel 1.6 Sistem Bilangan",
    des3:"\n\t\t",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/sistembil.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "9",
    bab: "bab 1",
    judul: "Konversi Bilangan Desimal ke Sistem Bilangan Biner",
    des1:"\n\t\tAda beberapa metode untuk mengkonversikan dari sistem bilangan desimal ke sistem bilangan biner. Metode pertama dan paling banyak digunakan adalah dengan cara membagi dengan nilai dua dan sisa setiap pembagian merupakan digit biner dan bilangan biner dari hasil konversi. Metode ini disebut metode sisa (remainder method).",
    des2:"\n\t\t",
    des3:"\n\t\tBila bilangan desimal yang akan dikonversikan berupa pecahan desimal, maka bilangan tersebut harus dipecah menjadi dua bagian, yaitu bilangan yang utuh dan yang pecahan. Misalnya bilangan desimal 125,4375 dipecah menjadi 125 dan 0,4375. Bilangan yang utuh, yaitu 125 dikonversikan terlebih dahulu ke bilangan biner, sebagal berikut.\n \n125 : 2 = 62 + sisa 1\n62   : 2 = 31 + sisa 0\n31   : 2 = 15 + sisa 1\n15   : 2 = 7 + sisa 1\n7\t: 2 = 3 + sisa 1\n3\t: 2 = 1 + sisa 1\n\n\t\tOleh karena itu, bilangan desimal 125 dalam bentuk bilangan biner adalah 111101. Kemudian bilangan yang pecahan dikonversikan kebilangan biner dengan cara yang berbeda seperti bilangan yang utuh, yaitu sebagai berikut.\n",
    des4:"\n\t\tJadi, bilangan desimal pecahan 0,4375 di dalam biner adalah 0,0111. Hasil dari bilangan :",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/destobiner.jpg"),
    tabel1:require("../../src/assets/materi/destobiner1.jpg"),
    tabel2:require("../../src/assets/materi/destobiner2.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "10",
    bab: "bab 1",
    judul: "Konversi Bilangan Desimal ke Sistem Bilangan Oktal",
    des1:"\n\t\tUntuk mengkonversikan bilangan desimal kebilangan oktaI dapat dipergunakan remainder method dengan pembaginya adalah basis dari bilangan oktal tersebut, yaitu 8. Misalnya bilangan desimal 385, dalam bilangan oktal bernilai:",
    des2:"\n\t\t",
    des3:"\n\t\t",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/destooctal.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "11",
    bab: "bab 1",
    judul: "Konversi Bilangan Desimal ke Sistem Bilangan Heksadesimal",
    des1:"\n\t\tDengan menggunakan remainder method, dengan pembaginya adalah basis dari bilangan heksadesimal, yaitu 16, maka bilangan desimal dapat dikonversikan ke bilangan heksadesimal. ",
    des2:"\n\t\t",
    des3:"\n\t\t",
    des4:"\n\t\t",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/destoheksa.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "12",
    bab: "bab 1",
    judul: "Konversi Bilangan Biner ke Sistem Bilangan Desimal",
    des1:"\n\t\tDari bilangan biner dapat dikonversikan ke bilangan desimal dengan cara mengalikan masing - masing bit dalam bilangan dengan nilai tempatnya.",
    des2:"t",
    des3:"",
    des4:"",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/binertodes.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "13",
    bab: "bab 1",
    judul: "Konversi Bilangan Biner ke Sistem Bilangan Oktal",
    des1:"\n\t\tKonversi dari bilangan biner ke bilangan oktal dapat dilakukan dengan mengkonversikan tiap- tiap tiga buah digit biner. Misalnya, bilangan biner 11010100 dapat dikonversikan ke oktal dengan cara :\n\n11 / 3\t\t 010 / 2\t\t100 / 4\n\nHubungan ini dapat dilihat pada tabel dibawah ini.\n",
    des2:"\n\t\tTabel 1.7 Konversi Bilangan Oktal",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/bintooctal.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "14",
    bab: "bab 1",
    judul: "Konversi Bilangan Biner ke Sistem Bilangan Heksadesimal",
    des1:"\n\t\tKonversi dari bilangan biner ke bilangan heksadesimal dapat dilakukan dengan mengkonversikan tiap-tiap empat buah digit biner.Misalnya bilangan biner 11010100 dapat dikonversikan ke bilangan heksadesimal dengan cara\n\n1101/D\t\t 0100/4\n\nHubungan ini dapat dilihat pada tabel berikut.\n",
    des2:"\n\t\tTabel 1.8 Konversi bit bilangan Heksadesimal",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/bintoheksa.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "15",
    bab: "bab 1",
    judul: "Konversi Bilangan Oktal ke Sistem Bilangan Desimal",
    des1:"\n\t\tBilangan oktal dapat dikonversikan ke bilangan desimal dengan cara mengalikan masing-masing bit dalam bilangan dengan nilai tempatnya.",
    des2:"\n\n\t\t",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/octaltodes.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "16",
    bab: "bab 1",
    judul: "Konversi Bilangan Oktal ke Sistem Bilangan Biner",
    des1:"\n\t\tKonversi dan bilangan oktal ke bilangan biner dapat dilakukan dengan mengkonversikanmasing-masing digit oktal ke 3 digit biner, sebagai berikut.",
    des2:"\n\t\t",
    des3:"\n\n\n\t\t",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/octaltobiner.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "17",
    bab: "bab 1",
    judul: "Konversi Bilangan Oktal ke Sistem Bilangan Heksadesimal",
    des1:"\n\t\tKonversi dan bilangan oktal ke bilangan heksadesimal dapat dilakukan dengan cara mengubah dari bilangan oktal menjadi bilangan biner terlebih dahulu, kemudian dikonversikan kebilanganheksadesimal. Misalnya, bilangan oktal 2537, akan dikonversikan ke heksadesimal, dengan langkah-langkahberikut ini.",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/octaltoheksa.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "18",
    bab: "bab 1",
    judul: "Konversi Bilangan Heksadesimal ke Sistem Bilangan Desimal",
    des1:"\n\t\tDari bilangan heksadesimal dapat dikonversikan ke bilangan desimal dengan cara mengalikanmasing-masing digit bilangan dengan nilai tempatnya.",
    des2:"\n\t\t",
    des3:"\n\t\tUntuk mengkonversikan bilangan heksadesimal ke bilangan desimal, dapat dengan bantuan table berikut.\n\nTabel 1.9 Hubungan nilai heksadesimal di posisi tertentu dengan nilai desimal",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/heksatodes.jpg"),
    tabel1:require("../../src/assets/materi/heksatodes1.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "19",
    bab: "bab 1",
    judul:"Konversi Bilangan Heksadesimal ke Sistem Bilangan Biner",
    des1:"\n\t\tKonversi dan hilangan heksadesimal ke sistem bilangan biner dapat dilakukan denganmengkonversikan masing-masing digit heksadesimal ke 4 digit biner sebagai berikut.",
    des2:"\n\t\t",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/heksatobiner.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "20",
    bab: "bab 1",
    judul:"Konversi Bilangan Heksadesimal ke Sistem Bilangan Oktal",
    des1:"\n\t\tKonversi dan bilangan heksadesimal ke bilangan oktal dapat dilakukan dengan cara mengubah dari bilangan heksadesimal menjadi bilangan biner terlebih dahulu, baru dikonversikan ke bilangan oktal.Misalnya bilangan heksadesimal 55F, akan dikonversikan ke oktal dengan Iangkah-Iangkah:",
    des2:"\n\t\t",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/heksatooctal.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "21",
    bab: "bab 1",
    judul: "Bentuk BCD ( Binary Coded Decimal)",
    des1:"\n\t\tBCD merupakan sistem sandi dengan 6 bit, sehingga kombinasi yang dapat digunakan sebagai sandi banyaknya adalah 2 pangkat 6 sama dengan 64 kombinasi. Pada transmisi sinkron sebuah karakter dibutuhkan 9 bit, yang terdiri dari 1 bit awal, 6 bit data, 1 bit paritas dan 1 bit akhir. (Kristanto, 2003, hal. 97)\n\n\t\tBCD (Binary Coded Decimal) merupakan kode biner yang digunakan hanya untuk mewakili nilai digit desimal saja, yaitu nilai angka 0 sampai dengan 9. BCD menggunakan kombinasi dari 4 bit, sehingga sebanyak 16 (24 = 16) kemungkinan kombinasi yang bisa diperoleh dan hanya 10 kombinasi yang digunakan.\n",
    des2:"\n\t\tTabel 1.10 BCD 4-bit",
    des3:"\n\t\tBilangan desimal pada setiap tempat dapat terdiri dari 10 bilangan yang berbeda- beda. Untuk bilangan biner, bentuk dari 10 elemen yang berbeda-beda memerlukan 4 bit. Sebuah BCD mempunyai 4 bit biner untuk setiap tempat bilangan desimal.",
    des4:"\n\t\tDalam contoh ini BCD terdiri dan 3 kelompok bilangan masing-masing terdiri dari 4 bit, dan jika bilangan desimal tersebut dikonversi ke dalam bilangan biner secara langsung adalah 31710 = 1001111012 dan hanya memerlukan 9 bit. Untuk contoh proses sebaliknya dapat dilihat di bawah ini.",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/bcd.jpg"),
    tabel1:require("../../src/assets/materi/bcd1.jpg"),
    tabel2:require("../../src/assets/materi/bcd2.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "22",
    bab: "bab 1",
    judul:"Bentuk BCH ( Binary Coded Hexadecimal)",
    des1:"\n\t\tBilangan heksadesimal dalam setiap tempat dapat terdiri dari 16 bilangan yang berbeda-beda angka dan huruf. Bentuk biner untuk 16 elemen memerlukan 4 bit.",
    des2:"\n\t\tTabel 1.11 BCH",
    des3:"\t\tSebuah BCH mempunyai 4 bit biner untuk setiap tempat bilangan heksadesimal.",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/bch.jpg"),
    tabel1:require("../../src/assets/materi/bch1.jpg"),
    video:"eQZzRbAXct8",
  },
  {
    id: "23",
    bab: "bab 1",
    judul:"ASCII Code-American Standard Code-for Information Interchange",
    des1:"\n\t\tDalam bidang komputer mikro, ASCII Code mempunyai arti yang sangat khusus, yaitu untuk mengkodekan karakter (huruf, angka, dan tanda baca yang Iainnya). Kode- kode ini merupakan kode standar yang dipakai oleh sebagian besar sistem komputer mikro. Selain huruf, angka dan tanda baca yang terdiri dari 32 karakter (contoh: ACK, NAK), ASCII Code merupakan kontrol untuk keperluan transportasi data. Di bawah ini adalah tabel 7 bit ASCII Code beserta beberapa penjelasan yang diperlukan.",
    des2:"\n\t\tTabel 1.12ACII Code 7 bit",
    des3:"\t\tASCII merupakan sandi 7 bit, sehingga terdapat 2 pangkat 7 yang berarti ada 128 macam simbol yang dapat disandikan dengan sistem sandi ini, sedangkan bit ke 8 merupakan bit paritas. Sandi ini dapat dikatakan yang paling banyak dipakai sebagai standard pensinyalan pada peralatan komunikasi data. Untuk transmisi asinkron tiap karakter disandikan dalam 10 atau 11 bit yang terdiri dari 1 bit awal, 7 bit data, 1 bit paritas, 1 atau 2 bit akhir.\n\nTabel 1.13 Sandi ASCII",
    image: require("../../src/assets/book.png"),
    tabel:require("../../src/assets/materi/ascii.jpg"),
    tabel1:require("../../src/assets/materi/ascii2.jpg"),
    video:"eQZzRbAXct8",
  },
];

export default materi;
